# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
import sys
# sys.path.insert(0, os.path.abspath('.'))

import sphinx.application
import sphinx.errors
sphinx.application.ExtensionError = sphinx.errors.ExtensionError


# -- Project information -----------------------------------------------------

project = '3gee医学'
copyright = '2022, 3gee'
author = '3gee'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'nbsphinx',
    "sphinx.ext.graphviz",
    'sphinxcontrib.kroki',
    'sphinxcontrib.googleanalytics',
    "sphinx_comments",
    'hoverxref.extension',
    "sphinx_panels",
    # 'sphinxnotes.any',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_book_theme'


footer_html = """\
<div class="container" id="footer-nav">
<div class="row">
<div class="col">
    <p style="text-align: center"><b>主站其他内容</b></p>
    <ul style="list-style-type: none; text-align: center; padding: 0;">
    <li><a href="https://blog.3gee.me/">我的博客<a></li>
    <li><a href="https://workwiki.3gee.me/">工作(DS/CS)百科<a></li>
    <li><a href="https://philosophia.3gee.me/">哲学百科<a></li>
    <li><a href="https://medicine.3gee.me/">医学百科<a></li>
    </ul>
</div>
<div class="col">
    <p style="text-align: center"><b>社交网络</b></p>
    <ul style="list-style-type: none; text-align: center; padding: 0;">
    <li><a href="https://www.zhihu.com/people/huang-bao-chen">知乎<a></li>
    <li><a href="https://stackoverflow.com/users/5387442/huang-baochen">StackOverflow<a></li>
    <li><a href="https://segmentfault.com/u/sancifanggen">SegmentFault<a></li>
    <li><a href="https://github.com/threecifanggen">GitHub<a></li>
    <ul>
</div>
<div class="col">
    <p style="text-align: center"><b>联系我</b></p>
    <ul style="list-style-type: none; text-align: center; padding: 0;">
    <li><a href="mailto:cube.root.huang+job@gmail.com">招聘<a></li>
    <li><a href="mailto:cube.root.huang+ask@gmail.com">社区求助(任何领域)<a></li>
    <ul>
</div>
</div></div>
"""

html_theme_options = {
    'repository_url' : 'https://github.com/threecifanggen/my-work-wiki',
    "use_repository_button": True,
    "show_navbar_depth": 1,
    "show_navbar_depth": 1,
    "use_fullscreen_button": True,
    "extra_footer": footer_html,
    "extra_navbar": '<p><b><a href="https://3gee.me">主站点</a></b><br/><b><a href="#footer-nav">页末导航</a></b></p>'
}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

source_suffix = {
    '.rst': 'restructuredtext',
    # '.txt': 'markdown',
    # '.md': 'markdown',
    '.myst.md': 'markdown',
}

myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

if sys.platform == 'win32':
    graphviz_dot_args = ['-Gfontname=Simsun', '-Efontname=Simsun', '-Nfontname=Simsun']

googleanalytics_id = "UA-56025474-5"

# 评论配置
comments_config = {
   "hypothesis": True,
   "utterances": {
      "repo": "threecifanggen/medicine-wiki",
      "issue-term": "pathname",
      "crossorigin": "anonymous",
      "theme": "github-light"
   }
}


html_search_language = 'zh'
# html_show_sourcelink = False

hoverxref_auto_ref = True

myst_html_meta = {
    "description lang=zh_CN": "黄宝臣(AKA 3GEE)的医学百科",
    "keywords": "3GEE, threecifanggen, 黄宝臣, 3gee, 医学百科",
}

# html_search_options = {
#     "dict": "dict/user_dict.txt"
# }

html_favicon = 'logo/3gee-logo.ico'
html_logo = "logo/3gee-logo-circle.png"
html_title = "3GEE医学百科"

panels_add_bootstrap_css = False